name: Develop build

on:
  pull_request:
    branches:
      - main
    paths:
      - images/custom/**
      - apps.json
      - .github/workflows/build_develop.yml

  schedule:
    # Every day at 12:00 pm
    - cron: 0 0 * * *

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/docker-build-push.yml
    with:
      frappe_branch: develop
      push: ${{ github.repository == 'tankerkiller125/frappe_docker' && github.event_name != 'pull_request' }}
      python_version: 3.14.2
      node_version: 24.12.0
