name: Stable build

on:
  pull_request:
    branches:
      - main
    paths:
      - images/custom/**
      - apps.json
      - .github/workflows/build_stable.yml

  push:
    branches:
      - main
    paths:
      - images/custom/**
      - apps.json

  # Triggered from frappe/frappe and frappe/erpnext on releases
  repository_dispatch:

  workflow_dispatch:

jobs:
  v16:
    uses: ./.github/workflows/docker-build-push.yml
    with:
      frappe_branch: version-16
      push: ${{ github.repository == 'tankerkiller125/frappe_docker' && github.event_name != 'pull_request' }}
      python_version: 3.14.2
      node_version: 24.12.0
